/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  dungeonsxl: [
    {
      type: 'category',
      label: 'DungeonsXL',
      items: [
        {
          type: 'autogenerated',
          dirName: 'dungeonsxl', 
        },
	  ],
    },
  ],
  qxl: [
    {
      type: 'category',
      label: 'QuestsXL',
      items: [
        {
          type: 'autogenerated',
          dirName: 'questsxl',
        },
	  ],
    },
  ],
  aether: [
    {
      type: 'category',
      label: 'Aether',
      items: [
        {
          type: 'autogenerated',
          dirName: 'aether',
        },
	  ],
    },
  ],
  aergia: [
    {
      type: 'category',
      label: 'Aergia',
      items: [
        {
          type: 'autogenerated',
          dirName: 'aergia',
        },
	  ],
    },
  ],
  itemsxl: [
    {
      type: 'category',
      label: 'ItemsXL',
      items: [
        {
          type: 'autogenerated',
          dirName: 'itemsxl',
        },
	  ],
    },
  ],
};

module.exports = sidebars;
